version: '3.9'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/github/kknock
    depends_on:
      - db

  db:
    image: mysql:8.0.36
    environment:
      MYSQL_ROOT_PASSWORD: 1207th
      MYSQL_DATABASE: kknock_db
      MYSQL_USER: ybell
      MYSQL_PASSWORD: gungail127
    ports:
      - "3306:3306"
       
